version: "3"

services:
  appointments:
    container_name: appointments
    build: .
    depends_on:
      - postgres
    links:
      - postgres
    command: npm start
    ports:
      - 3003:3003
    volumes:
      - .:/usr/appointments
      - /usr/appointments/node_modules
    environment:
      NODE_ENV: start
      PORT: 3003
  postgres:
    container_name: postgres
    image: postgres:13
    ports:
      - "65432:5432"
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
