version: "3"

services:
  appointments:
    container_name: appointments
    build: .
    depends_on:
      - postgres
    links:
      - postgres
    command: npm run start:dev
    ports:
      - 3003:3003
      - 9229:9229
    volumes:
      - .:/usr/appointments
      - /usr/appointments/node_modules
    environment:
      NODE_ENV: dev
      PORT: 3003
  postgres:
    container_name: postgres
    image: postgres:13
    ports:
      - "65432:5432"
    env_file: .env.dev
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
